export const ModuleName =  "search"

export const Action = {
    SEARCH_IMAGE_POSTS: "SEARCH_IMAGE_POSTS",
    LIKE_IMAGE_POST: "LIKE_IMAGE_POST",
    UNLIKE_IMAGE_POST: "UNLIKE_IMAGE_POST",
    DELETE_IMAGE_POST: "DELETE_IMAGE_POST"
}

export const Mutation = {
    SET_IMAGE_POSTS: "SET_IMAGE_POSTS",
    SET_IS_LOADING: "SET_IS_LOADING",
    ADD_LIKE_TO_IMAGE_POST: "ADD_LIKE_TO_IMAGE_POST",
    REMOVE_LIKE_FROM_IMAGE_POST: "REMOVE_LIKE_FROM_IMAGE_POST",
    REMOVE_IMAGE_POST_FROM_SEARCH: "REMOVE_IMAGE_POST_FROM_SEARCH"
}