export const ModuleName = "user"

export const Action = {
    ADD_FOLLOWING: "ADD_FOLLOWING",
    REMOVE_FOLLOWING_BY_USERNAME: "REMOVE_FOLLOWING_BY_USERNAME"
}

export const Mutation = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    ADD_FOLLOWING_TO_CURRENT_USER: "ADD_FOLLOWING_TO_CURRENT_USER",
    REMOVE_FOLLOWING_BY_USERNAME_FROM_CURRENT_USER: "REMOVE_FOLLOWING_BY_USERNAME_FROM_CURRENT_USER"
}