image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test

before_script:
  - "cd src/api"
  - "dotnet restore"

build-api:
  stage: build
  script:
    - "dotnet build"
    
test-api:
  stage: test
  script: 
    - "dotnet test"