export const ModuleName = "imagePosts"

export const Action = {
    LIKE_IMAGE_POST: "LIKE_IMAGE_POST",
    UNLIKE_IMAGE_POST: "UNLIKE_IMAGE_POST",
    CREATE_IMAGE_POST_COMMENT: "CREATE_IMAGE_POST_COMMENT",
    UPDATE_IMAGE_POST_COMMENT: "UPDATE_IMAGE_POST_COMMENT",
    DELETE_IMAGE_POST_COMMENT: "DELETE_IMAGE_POST_COMMENT",
    FETCH_IMAGE_POST_BY_ID: "FETCH_IMAGE_POST_BY_ID",
    CREATE_IMAGE_POST: "CREATE_IMAGE_POST",
    UPDATE_IMAGE_POST: "UPDATE_IMAGE_POST",
    DELETE_IMAGE_POST: "DELETE_IMAGE_POST"
}

export const Mutation = {
    UPDATE_IMAGE_POSTS: "UPDATE_IMAGE_POSTS",
    ADD_LIKE_TO_IMAGE_POST: "ADD_LIKE_TO_IMAGE_POST",
    REMOVE_LIKE_FROM_IMAGE_POST: "REMOVE_LIKE_FROM_IMAGE_POST",
    ADD_COMMENT_TO_IMAGE_POST: "ADD_COMMENT_TO_IMAGE_POST",
    UPDATE_COMMENT_ON_IMAGE_POST: "UPDATE_COMMENT_ON_IMAGE_POST",
    REMOVE_COMMENT_FROM_IMAGE_POST: "REMOVE_COMMENT_FROM_IMAGE_POST",
    REMOVE_IMAGE_POST: "REMOVE_IMAGE_POST"
}