export const ModuleName = "feed"

export const Action = {
    GET_FEED: "GET_FEED",
    LIKE_IMAGE_POST: "LIKE_IMAGE_POST",
    UNLIKE_IMAGE_POST: "UNLIKE_IMAGE_POST",
    CREATE_IMAGE_POST_COMMENT: "CREATE_IMAGE_POST_COMMENT",
    UPDATE_IMAGE_POST_COMMENT: "UPDATE_IMAGE_POST_COMMENT",
    DELETE_IMAGE_POST_COMMENT: "DELETE_IMAGE_POST_COMMENT",
}

export const Mutation = {
    SET_IMAGE_POSTS: "SET_IMAGE_POSTS",
    ADD_LIKE_TO_IMAGE_POST: "ADD_LIKE_TO_IMAGE_POST",
    REMOVE_LIKE_FROM_IMAGE_POST: "REMOVE_LIKE_FROM_IMAGE_POST",
    ADD_COMMENT_TO_IMAGE_POST: "ADD_COMMENT_TO_IMAGE_POST",
    UPDATE_COMMENT_ON_IMAGE_POST: "UPDATE_COMMENT_ON_IMAGE_POST",
    REMOVE_COMMENT_FROM_IMAGE_POST: "REMOVE_COMMENT_FROM_IMAGE_POST",
    SET_IS_LOADING: "SET_IS_LOADING"
}