export const ModuleName = "feed"

export const Action = {
    GET_FEED: "GET_FEED",
    ADD_NEW_IMAGE_POST_ID: "ADD_NEW_IMAGE_POST_ID",
    REMOVE_IMAGE_POST_ID: "REMOVE_IMAGE_POST_ID"
}

export const Mutation = {
    SET_IMAGE_POST_IDS: "SET_IMAGE_POST_IDS",
    ADD_IMAGE_POST_ID_TO_BEGINNING: "ADD_IMAGE_POST_ID_TO_BEGINNING",
    REMOVE_IMAGE_POST_ID: "REMOVE_IMAGE_POST_ID"
}