export const ModuleName =  "profile"

export const Action = {
    GET_PROFILE_BY_USERNAME: "GET_PROFILE_BY_USERNAME",
    FOLLOW_PROFILE: "FOLLOW_PROFILE",
    UNFOLLOW_PROFILE: "UNFOLLOW_PROFILE",
    LIKE_IMAGE_POST: "LIKE_IMAGE_POST",
    UNLIKE_IMAGE_POST: "UNLIKE_IMAGE_POST",
    DELETE_IMAGE_POST: "DELETE_IMAGE_POST"
}

export const Mutation = {
    SET_PROFILE: "SET_PROFILE",
    SET_PROFILE_USERNAME: "SET_PROFILE_USERNAME",
    SET_PROFILE_NOT_FOUND: "SET_PROFILE_NOT_FOUND",
    SET_IS_LOADING: "SET_IS_LOADING",
    ADD_FOLLOW_TO_PROFILE: "ADD_FOLLOW_TO_PROFILE",
    REMOVE_FOLLOW_FROM_PROFILE: "REMOVE_FOLLOW_FROM_PROFILE",
    ADD_LIKE_TO_IMAGE_POST: "ADD_LIKE_TO_IMAGE_POST",
    REMOVE_LIKE_FROM_IMAGE_POST: "REMOVE_LIKE_FROM_IMAGE_POST",
    REMOVE_IMAGE_POST_FROM_PROFILE: "REMOVE_IMAGE_POST_FROM_PROFILE"
}