export const ModuleName =  "profile"

export const Action = {
    GET_PROFILE_BY_USERNAME: "GET_PROFILE_BY_USERNAME",
    FOLLOW_PROFILE: "FOLLOW_PROFILE",
    UNFOLLOW_PROFILE: "UNFOLLOW_PROFILE",
    DELETE_IMAGE_POST: "DELETE_IMAGE_POST"
}

export const Mutation = {
    SET_PROFILE: "SET_PROFILE",
    SET_IMAGE_POST_IDS: "SET_IMAGE_POST_IDS",
    SET_PROFILE_USERNAME: "SET_PROFILE_USERNAME",
    SET_PROFILE_NOT_FOUND: "SET_PROFILE_NOT_FOUND",
    ADD_FOLLOWER_TO_PROFILE: "ADD_FOLLOWER_TO_PROFILE",
    REMOVE_FOLLOWER_FROM_PROFILE: "REMOVE_FOLLOWER_FROM_PROFILE",
    REMOVE_IMAGE_POST_FROM_PROFILE: "REMOVE_IMAGE_POST_FROM_PROFILE"
}