export const Action = {
    FETCH_IMAGE_POST_BY_ID: "EXPLORE_FETCH_IMAGE_POST_BY_ID",
    FETCH_RANDOM_IMAGE_POST: "EXPLORE_FETCH_RANDOM_IMAGE_POST",
    NEXT_IMAGE_POST: "EXPLORE_NEXT_IMAGE_POST",
    PREVIOUS_IMAGE_POST: "EXPLORE_PREVIOUS_IMAGE_POST"
}

export const Mutation = {
    ADD_IMAGE_POST: "EXPLORE_ADD_IMAGE_POST",
    SET_CURRENT_IMAGE_POST_INDEX: "EXPLORE_SET_CURRENT_IMAGE_POST_INDEX",
    SET_NO_IMAGE_POSTS_AVAILABLE: "EXPLORE_SET_NO_IMAGE_POSTS_AVAILABLE",
    SET_IMAGE_POST_NOT_FOUND: "EXPLORE_SET_IMAGE_POST_NOT_FOUND",
    SET_IS_LOADING: "EXPLORE_SET_IS_LOADING",
}