export const ModuleName = "explore"

export const Action = {
    VIEW_IMAGE_POST_BY_ID: "VIEW_IMAGE_POST_BY_ID",
    VIEW_RANDOM_IMAGE_POST: "VIEW_RANDOM_IMAGE_POST",
    VIEW_IMAGE_POST: "VIEW_IMAGE_POST",
    NEXT_IMAGE_POST: "NEXT_IMAGE_POST",
    PREVIOUS_IMAGE_POST: "PREVIOUS_IMAGE_POST",
    DELETE_IMAGE_POST: "DELETE_IMAGE_POST",
    REMOVE_IMAGE_POST_BY_ID: "REMOVE_IMAGE_POST_BY_ID"
}

export const Mutation = {
    ADD_IMAGE_POST_ID: "ADD_IMAGE_POST_ID",
    REMOVE_IMAGE_POST_ID: "REMOVE_IMAGE_POST_ID",
    SET_CURRENT_IMAGE_POST_INDEX: "SET_CURRENT_IMAGE_POST_INDEX",
    SET_NO_IMAGE_POSTS_AVAILABLE: "SET_NO_IMAGE_POSTS_AVAILABLE",
    SET_IMAGE_POST_NOT_FOUND: "SET_IMAGE_POST_NOT_FOUND",
    SET_IS_LOADING: "SET_IS_LOADING"
}