name: Show 'N Tell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      API_WORKING_DIRECTORY: ./src/api
      BUILD_CONFIGURATION: Release
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_REGISTRY_USERNAME: showntellapi
      AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      DATABASE: ${{ secrets.DATABASE }}
      BLOB_STORAGE: ${{ secrets.BLOB_STORAGE }}
      APPLICATION_INSIGHTS_KEY: ${{ secrets.APPLICATION_INSIGHTS_KEY }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Login to Azure
      if: github.event_name != 'pull_request'
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      if: github.event_name != 'pull_request'
      run: docker login showntellapi.azurecr.io -u ${{ env.AZURE_REGISTRY_USERNAME }} -p ${{ env.AZURE_REGISTRY_PASSWORD }}
        
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{ env.API_WORKING_DIRECTORY }}
        
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
      working-directory: ${{ env.API_WORKING_DIRECTORY }}
        
    - name: Test
      run: dotnet test --no-build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
      working-directory: ${{ env.API_WORKING_DIRECTORY }}

    - name: Build Docker Image
      if: github.event_name != 'pull_request'
      run: docker build --rm -f "src/api/Dockerfile" -t showntellapi.azurecr.io/api "src/api" --build-arg DATABASE="${{ env.DATABASE }}" --build-arg BLOB_STORAGE="${{ env.BLOB_STORAGE }}" --build-arg APPLICATION_INSIGHTS_KEY="${{ env.APPLICATION_INSIGHTS_KEY }}"

    - name: Deploy to Azure Container Registry
      if: github.event_name != 'pull_request'
      run: docker push showntellapi.azurecr.io/api

    - name: Deploy to Azure Container Instance
      if: github.event_name != 'pull_request'
      uses: azure/CLI@v1
      with:
        inlineScript: az container restart --name showntellapi --resource-group show-n-tell